Update docker_build_push.yml

diff --git a/.github/workflows/docker_build_push.yml b/.github/workflows/docker_build_push.yml
--- a/.github/workflows/docker_build_push.yml
+++ b/.github/workflows/docker_build_push.yml
@@ -1,4 +1,4 @@
-name: Build and Push Docker Image
+name: Build, Train, Push, Pull and Test
 
 on:
   pull_request:
@@ -7,7 +7,7 @@ on:
       - synchronize
 
 jobs:
-  build_and_push:
+  Train:
     runs-on: ubuntu-latest
 
     steps:
@@ -15,7 +15,13 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Build Docker image
-        run: docker build -t my-image-name .
+        run: docker build -t vikrammupparthi/myimage:v1 .
+
+      - name: Run Docker container
+        run: docker run vikrammupparthi/myimage:v1
+      
+      - name: Tag Docker image
+        run: docker tag vikrammupparthi/myimage:v1 vikrammupparthi/mlopsassignment:v1    
 
       - name: Log in to Docker registry
         uses: docker/login-action@v1
@@ -25,4 +31,44 @@ jobs:
           password: dckr_pat_wQAkR2ot49kqygLZdDZ_Kw7Kc-w
 
       - name: Push Docker image
-        run: docker push my-image-name
+        run: docker push vikrammupparthi/mlopsassignment:v1
+
+  Test:
+    name: Pull Docker Image
+    runs-on: ubuntu-latest
+    needs: Train
+    
+    steps:
+         - name: Checkout code
+           uses: actions/checkout@v2
+
+         - name: Log in to Docker registry
+           uses: docker/login-action@v1
+           with:
+             registry: docker.io
+             username: vikrammupparthi
+             password: dckr_pat_wQAkR2ot49kqygLZdDZ_Kw7Kc-w
+ 
+         - name: Pull Docker image
+           run: docker pull vikrammupparthi/mlopsassignment:v1
+
+         - name: Run Docker container
+           run: docker run vikrammupparthi/mlopsassignment:v1 > output.txt
+
+         - name: Analyze Output and Set Workflow Status
+           run: |
+            # Extract the score from output.txt
+            score=$(cat output.txt)
+            
+            # Define the threshold
+            threshold=0.3 # Adjust this threshold value as per your requirement
+            
+            # Compare the score with the threshold
+            if [ $(echo "$score > $threshold" | bc) -eq 1 ]; then
+              echo "Score:"
+              echo $score
+              exit 0  # Mark the workflow as successful
+            else
+              echo "Insufficient Accuracy"
+              exit 1  # Mark the workflow as failed
+            fi
